apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart: cert-manager
  version: v1.1.0
  sourceRef:
    name: jetstack
    kind: HelmRepository
  interval: 1m